import { useQuery } from '@tanstack/react-query';
import { supabase, hasSupabaseConfig } from '@/shared/api/supabase-client';
import type { Database } from '@/shared/types/database.types';
import { Debug } from '@/shared/utils/debug';
import dayjs from 'dayjs';

type Product = Database['public']['Tables']['products']['Row'];
type Category = Database['public']['Tables']['categories']['Row'];

// Type for fallback data structure (compatible with old products table)
type MenuItemWithCategory = Product & { categories: Category | null };

// Production menu data - used when Supabase is not configured or as fallback
const MENU_PRODUCTS: MenuItemWithCategory[] = [
  {
    id: 'menu-1',
    name: 'Sườn non ram mặn',
    description: '',
    price: 35000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-1',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-1',
      name: 'Thịt',
      slug: 'thit',
      image_url: null,
      sort_order: 1,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-2',
    name: 'Sườn muối sả chiên',
    description: '',
    price: 45000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-1',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-1',
      name: 'Thịt',
      slug: 'thit',
      image_url: null,
      sort_order: 1,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-3',
    name: 'Ba rọi chiên nước mắm',
    description: '',
    price: 35000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-1',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-1',
      name: 'Thịt',
      slug: 'thit',
      image_url: null,
      sort_order: 1,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-4',
    name: 'Thịt kho trứng',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-1',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-1',
      name: 'Thịt',
      slug: 'thit',
      image_url: null,
      sort_order: 1,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-5',
    name: 'Thịt kho tiêu',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-1',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-1',
      name: 'Thịt',
      slug: 'thit',
      image_url: null,
      sort_order: 1,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-6',
    name: 'Thịt xào mắm ruốc',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-1',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-1',
      name: 'Thịt',
      slug: 'thit',
      image_url: null,
      sort_order: 1,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-7',
    name: 'Sườn + trứng - chiên',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-1',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-1',
      name: 'Thịt',
      slug: 'thit',
      image_url: null,
      sort_order: 1,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-8',
    name: 'Sườn chiên',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-1',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-1',
      name: 'Thịt',
      slug: 'thit',
      image_url: null,
      sort_order: 1,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-9',
    name: 'Sườn nướng',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-1',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-1',
      name: 'Thịt',
      slug: 'thit',
      image_url: null,
      sort_order: 1,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-10',
    name: 'Cá sát kho',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-2',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-2',
      name: 'Cá',
      slug: 'ca',
      image_url: null,
      sort_order: 2,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-11',
    name: 'Cá ngừ kho khóm',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-2',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-2',
      name: 'Cá',
      slug: 'ca',
      image_url: null,
      sort_order: 2,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-12',
    name: 'Cá bạc má muối chiên',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-2',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-2',
      name: 'Cá',
      slug: 'ca',
      image_url: null,
      sort_order: 2,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-13',
    name: 'Cá nục kho cà',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-2',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-2',
      name: 'Cá',
      slug: 'ca',
      image_url: null,
      sort_order: 2,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-14',
    name: 'Cá nục chiên sốt cà chua',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-2',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-2',
      name: 'Cá',
      slug: 'ca',
      image_url: null,
      sort_order: 2,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-15',
    name: 'Cá tra kho',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-2',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-2',
      name: 'Cá',
      slug: 'ca',
      image_url: null,
      sort_order: 2,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-16',
    name: 'Cá tra muối chiên',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-2',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-2',
      name: 'Cá',
      slug: 'ca',
      image_url: null,
      sort_order: 2,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-17',
    name: 'Cá cơm - mồm kho lạt (xoài bằm)',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-2',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-2',
      name: 'Cá',
      slug: 'ca',
      image_url: null,
      sort_order: 2,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-18',
    name: 'Cá điêu hồng chiên (mắm xoài)',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-2',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-2',
      name: 'Cá',
      slug: 'ca',
      image_url: null,
      sort_order: 2,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-19',
    name: 'Cá lưỡi trâu muối chiên',
    description: '',
    price: 35000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-2',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-2',
      name: 'Cá',
      slug: 'ca',
      image_url: null,
      sort_order: 2,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-20',
    name: 'Cá điêu hồng chiên sốt tương',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-2',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-2',
      name: 'Cá',
      slug: 'ca',
      image_url: null,
      sort_order: 2,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-21',
    name: 'Khô cá dứa chiên',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-2',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-2',
      name: 'Cá',
      slug: 'ca',
      image_url: null,
      sort_order: 2,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-22',
    name: 'Cá he kho lạt',
    description: '',
    price: 35000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-2',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-2',
      name: 'Cá',
      slug: 'ca',
      image_url: null,
      sort_order: 2,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-23',
    name: 'Cá he kho - mềm xương',
    description: '',
    price: 45000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-2',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-2',
      name: 'Cá',
      slug: 'ca',
      image_url: null,
      sort_order: 2,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-24',
    name: 'Cá cơm chiên bột',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-2',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-2',
      name: 'Cá',
      slug: 'ca',
      image_url: null,
      sort_order: 2,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-25',
    name: 'Cá lăn kho tiêu',
    description: '',
    price: 35000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-2',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-2',
      name: 'Cá',
      slug: 'ca',
      image_url: null,
      sort_order: 2,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-26',
    name: 'Cá trê chiên (mắm gừng)',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-2',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-2',
      name: 'Cá',
      slug: 'ca',
      image_url: null,
      sort_order: 2,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-27',
    name: 'Cá trê kho tiêu',
    description: '',
    price: 35000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-2',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-2',
      name: 'Cá',
      slug: 'ca',
      image_url: null,
      sort_order: 2,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-28',
    name: 'Cá rô kho',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-2',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-2',
      name: 'Cá',
      slug: 'ca',
      image_url: null,
      sort_order: 2,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-29',
    name: 'Cá rô kho bầu',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-2',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-2',
      name: 'Cá',
      slug: 'ca',
      image_url: null,
      sort_order: 2,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-30',
    name: 'Cá lóc kho',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-2',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-2',
      name: 'Cá',
      slug: 'ca',
      image_url: null,
      sort_order: 2,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-31',
    name: 'Cá lóc muối chiên',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-2',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-2',
      name: 'Cá',
      slug: 'ca',
      image_url: null,
      sort_order: 2,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-32',
    name: 'Canh chua cá tra',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-3',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-3',
      name: 'Canh',
      slug: 'canh',
      image_url: null,
      sort_order: 3,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-33',
    name: 'Canh chua cá lóc',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-3',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-3',
      name: 'Canh',
      slug: 'canh',
      image_url: null,
      sort_order: 3,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-34',
    name: 'Canh chua đầu cá lóc',
    description: '',
    price: 45000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-3',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-3',
      name: 'Canh',
      slug: 'canh',
      image_url: null,
      sort_order: 3,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-35',
    name: 'Canh khổ qua',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-3',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-3',
      name: 'Canh',
      slug: 'canh',
      image_url: null,
      sort_order: 3,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-36',
    name: 'Canh chua cá điêu hồng',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-3',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-3',
      name: 'Canh',
      slug: 'canh',
      image_url: null,
      sort_order: 3,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-37',
    name: 'Canh gà lá giang',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-3',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-3',
      name: 'Canh',
      slug: 'canh',
      image_url: null,
      sort_order: 3,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-38',
    name: 'Vịt xào gừng',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-4',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-4',
      name: 'Vịt & Gà',
      slug: 'vit-ga',
      image_url: null,
      sort_order: 4,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-39',
    name: 'Gà xào sả ớt',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-4',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-4',
      name: 'Vịt & Gà',
      slug: 'vit-ga',
      image_url: null,
      sort_order: 4,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-40',
    name: 'Đùi gà chiên nước mắm',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-4',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-4',
      name: 'Vịt & Gà',
      slug: 'vit-ga',
      image_url: null,
      sort_order: 4,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-41',
    name: 'Trứng chiên hành',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-5',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-5',
      name: 'Khác',
      slug: 'khac',
      image_url: null,
      sort_order: 5,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-42',
    name: 'Tép gạo ram mặm',
    description: '',
    price: 35000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-5',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-5',
      name: 'Khác',
      slug: 'khac',
      image_url: null,
      sort_order: 5,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-43',
    name: 'Hến xào sả ớt',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-5',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-5',
      name: 'Khác',
      slug: 'khac',
      image_url: null,
      sort_order: 5,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-44',
    name: 'Hến xào cuộn trứng',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-5',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-5',
      name: 'Khác',
      slug: 'khac',
      image_url: null,
      sort_order: 5,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-45',
    name: 'Thịt bằm cuộn trứng',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-5',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-5',
      name: 'Khác',
      slug: 'khac',
      image_url: null,
      sort_order: 5,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-46',
    name: 'Lươn xào sả ớt',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-5',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-5',
      name: 'Khác',
      slug: 'khac',
      image_url: null,
      sort_order: 5,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-47',
    name: 'Ếch xào sả ớt',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-5',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-5',
      name: 'Khác',
      slug: 'khac',
      image_url: null,
      sort_order: 5,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-48',
    name: 'Ếch xào nghệ',
    description: '',
    price: 30000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-5',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-5',
      name: 'Khác',
      slug: 'khac',
      image_url: null,
      sort_order: 5,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-49',
    name: 'Sườn chay chiên giòn',
    description: '',
    price: 20000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-6',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-6',
      name: 'Chay',
      slug: 'chay',
      image_url: null,
      sort_order: 6,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-50',
    name: 'Đậu hủ xào đậu que',
    description: '',
    price: 20000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-6',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-6',
      name: 'Chay',
      slug: 'chay',
      image_url: null,
      sort_order: 6,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-51',
    name: 'Đậu hủ chiên sả',
    description: '',
    price: 20000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-6',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-6',
      name: 'Chay',
      slug: 'chay',
      image_url: null,
      sort_order: 6,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-52',
    name: 'Đậu chiên giòn',
    description: '',
    price: 20000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-6',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-6',
      name: 'Chay',
      slug: 'chay',
      image_url: null,
      sort_order: 6,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-53',
    name: 'Đậu hủ kho rau củ',
    description: '',
    price: 20000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-6',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-6',
      name: 'Chay',
      slug: 'chay',
      image_url: null,
      sort_order: 6,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-54',
    name: 'Đậu hủ xào cải muối',
    description: '',
    price: 20000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-6',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-6',
      name: 'Chay',
      slug: 'chay',
      image_url: null,
      sort_order: 6,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-55',
    name: 'Khổ qua xào trứng',
    description: '',
    price: 20000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-7',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-7',
      name: 'Món Xào',
      slug: 'mon-xao',
      image_url: null,
      sort_order: 7,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-56',
    name: 'Bò xào khổ qua',
    description: '',
    price: 35000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-7',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-7',
      name: 'Món Xào',
      slug: 'mon-xao',
      image_url: null,
      sort_order: 7,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-57',
    name: 'Bò xào bông cải',
    description: '',
    price: 35000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-7',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-7',
      name: 'Món Xào',
      slug: 'mon-xao',
      image_url: null,
      sort_order: 7,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'menu-58',
    name: 'Bò xào đậu que',
    description: '',
    price: 35000,
    image_url: '/images/menu/placeholder.png',
    category_id: 'cat-7',
    is_active: true,
    is_sold_out: false,
    stock_quantity: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: {
      id: 'cat-7',
      name: 'Món Xào',
      slug: 'mon-xao',
      image_url: null,
      sort_order: 7,
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
];

const MENU_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Thịt',
    slug: 'thit',
    image_url: null,
    sort_order: 1,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-2',
    name: 'Cá',
    slug: 'ca',
    image_url: null,
    sort_order: 2,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-3',
    name: 'Canh',
    slug: 'canh',
    image_url: null,
    sort_order: 3,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-4',
    name: 'Vịt & Gà',
    slug: 'vit-ga',
    image_url: null,
    sort_order: 4,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-5',
    name: 'Khác',
    slug: 'khac',
    image_url: null,
    sort_order: 5,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-6',
    name: 'Chay',
    slug: 'chay',
    image_url: null,
    sort_order: 6,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-7',
    name: 'Món Xào',
    slug: 'mon-xao',
    image_url: null,
    sort_order: 7,
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

export const useAllMenuItems = () => {
  return useQuery({
    queryKey: ['all-menu-items'],
    queryFn: async () => {
      // Return production menu if Supabase is not configured
      if (!hasSupabaseConfig) {
        Debug.warn('⚠️ Supabase not configured - showing production menu');
        return MENU_PRODUCTS;
      }

      try {
        // Try to fetch from menu_items table first (new schema with 110 items)
        const { data: menuData, error: menuError } = await supabase
          .from('menu_items')
          .select(
            `
            *,
            categories (
              id,
              name,
              slug,
              sort_order
            )
          `
          )
          .eq('is_active', true)
          .order('name');

        if (!menuError && menuData) {
          Debug.log(`✅ Loaded ${menuData.length} items from menu_items table`);
          // Convert menu_items format to Product format for compatibility
          return menuData.map((item) => ({
            id: item.id.toString(), // Convert number to string
            category_id: item.category_id,
            name: item.name,
            description: item.description,
            price: item.price,
            image_url: item.image_url,
            is_active: item.is_active,
            is_sold_out: item.is_sold_out,
            created_at: item.created_at,
            updated_at: item.updated_at,
            categories: item.categories as Category | null,
          })) as MenuItemWithCategory[];
        }

        // Fallback to old products table if menu_items doesn't exist
        const { data: productsData, error: productsError } = await supabase
          .from('products')
          .select(
            `
            *,
            categories (
              id,
              name,
              sort_order
            )
          `
          )
          .eq('is_active', true)
          .order('name');

        if (productsError) {
          Debug.warn('⚠️ Supabase error - falling back to production menu:', productsError.message);
          return MENU_PRODUCTS;
        }

        return productsData as MenuItemWithCategory[];
      } catch (err) {
        // Catch any network or auth errors and fallback to production
        Debug.warn('⚠️ Failed to fetch menu - falling back to production:', err);
        return MENU_PRODUCTS;
      }
    },
  });
};

// Hook for /menu page - shows only items selected by admin for TODAY
export const useDailyMenu = () => {
  const today = dayjs().format('YYYY-MM-DD');

  return useQuery({
    queryKey: ['daily-menu', today],
    queryFn: async () => {
      // In demo mode (no Supabase), show all items as daily menu
      if (!hasSupabaseConfig) {
        Debug.warn('⚠️ Supabase not configured - showing all items as daily menu');
        return MENU_PRODUCTS;
      }

      try {
        // Step 1: Fetch today's daily menu selections from daily_menus table
        const { data: dailySelections, error: dailyError } = await supabase
          .from('daily_menus')
          .select('product_id')
          .eq('date', today)
          .eq('is_active', true);

        // If error or no daily menu set for today, return empty array
        if (dailyError) {
          Debug.warn('⚠️ Error fetching daily menu:', dailyError.message);
          return [];
        }

        if (!dailySelections || dailySelections.length === 0) {
          Debug.log('📋 No daily menu set for today - showing empty state');
          return [];
        }

        // Step 2: Fetch the actual product details for today's selections
        const productIds = dailySelections.map((d) => d.product_id);

        // Try menu_items first
        const { data: menuData, error: menuError } = await supabase
          .from('menu_items')
          .select(
            `
            *,
            categories (
              id,
              name,
              slug,
              sort_order
            )
          `
          )
          .in('id', productIds)
          .eq('is_active', true);

        if (!menuError && menuData && menuData.length > 0) {
          Debug.log(`✅ Loaded ${menuData.length} daily menu items`);
          return menuData.map((item) => ({
            id: item.id.toString(),
            category_id: item.category_id,
            name: item.name,
            description: item.description,
            price: item.price,
            image_url: item.image_url,
            is_active: item.is_active,
            is_sold_out: item.is_sold_out,
            created_at: item.created_at,
            updated_at: item.updated_at,
            categories: item.categories as Category | null,
          })) as MenuItemWithCategory[];
        }

        // Fallback to products table
        const { data: productsData, error: productsError } = await supabase
          .from('products')
          .select(
            `
            *,
            categories (
              id,
              name,
              sort_order
            )
          `
          )
          .in('id', productIds)
          .eq('is_active', true);

        if (productsError || !productsData) {
          Debug.warn('⚠️ Error fetching products:', productsError?.message);
          return [];
        }

        return productsData as MenuItemWithCategory[];
      } catch (err) {
        Debug.warn('⚠️ Failed to fetch daily menu:', err);
        return [];
      }
    },
  });
};

export const useCategories = () => {
  return useQuery({
    queryKey: ['categories'],
    queryFn: async () => {
      // Return production categories if Supabase is not configured
      if (!hasSupabaseConfig) {
        Debug.warn('⚠️ Supabase not configured - showing production categories');
        return MENU_CATEGORIES;
      }

      try {
        const { data, error } = await supabase
          .from('categories')
          .select('*')
          .eq('is_active', true)
          .order('sort_order');

        // If error from Supabase (e.g., 401 with placeholder credentials), fallback to production
        if (error) {
          Debug.warn('⚠️ Supabase error - falling back to production categories:', error.message);
          return MENU_CATEGORIES;
        }

        return data as Category[];
      } catch (err) {
        // Catch any network or auth errors and fallback to production
        Debug.warn('⚠️ Failed to fetch categories - falling back to production:', err);
        return MENU_CATEGORIES;
      }
    },
  });
};
