-- =====================================================
-- CHECKOUT LOYALTY INTEGRATION
-- Created: 2026-01-31
-- =====================================================

-- 1. Add points_redeemed to orders
ALTER TABLE public.orders
ADD COLUMN IF NOT EXISTS points_redeemed INTEGER DEFAULT 0;

-- 2. Trigger to Deduct Points on Order Creation
CREATE OR REPLACE FUNCTION process_point_redemption()
RETURNS TRIGGER AS $$
DECLARE
    v_customer_id UUID;
    v_current_points INTEGER;
    v_discount_amount INTEGER;
BEGIN
    -- Only process if points are being redeemed
    IF NEW.points_redeemed > 0 THEN
        v_customer_id := NEW.customer_id;

        -- Validate customer
        IF v_customer_id IS NULL THEN
            RAISE EXCEPTION 'Cannot redeem points for guest orders';
        END IF;

        -- Check balance
        SELECT points INTO v_current_points
        FROM public.customers
        WHERE id = v_customer_id;

        IF v_current_points IS NULL OR v_current_points < NEW.points_redeemed THEN
            RAISE EXCEPTION 'Insufficient points balance';
        END IF;

        -- Deduct points
        UPDATE public.customers
        SET points = points - NEW.points_redeemed
        WHERE id = v_customer_id;

        -- Log transaction
        -- Note: We log the discount value for reference.
        -- Assuming 1 Point = 100 VND (Consistent with previous RPC)
        v_discount_amount := NEW.points_redeemed * 100;

        INSERT INTO public.loyalty_transactions (customer_id, order_id, type, points, description)
        VALUES (
            v_customer_id,
            NEW.id, -- This ID is available in BEFORE INSERT if it's UUID generated by client or default?
                    -- Wait, BEFORE INSERT, NEW.id might be generated by DEFAULT uuid_generate_v4().
                    -- Postgres allows accessing NEW.id if it's generated.
            'redeem',
            -NEW.points_redeemed,
            'Redeemed ' || NEW.points_redeemed || ' points for Order discount'
        );

    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 3. Attach Trigger
DROP TRIGGER IF EXISTS trg_deduct_points_on_order ON public.orders;
CREATE TRIGGER trg_deduct_points_on_order
    BEFORE INSERT ON public.orders
    FOR EACH ROW
    EXECUTE FUNCTION process_point_redemption();

-- 4. Update Orders RLS to allow inserting with points_redeemed
-- (Existing policies might already allow it if they are broad, checking...)
-- The initial schema didn't explicitely restrict columns, but good to verify.
