-- =====================================================
-- PAYMENT TRANSACTIONS SCHEMA
-- Created: 2026-01-31
-- =====================================================

-- Table Definition
CREATE TABLE IF NOT EXISTS public.payment_transactions (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    order_id UUID REFERENCES public.orders(id) NOT NULL,
    provider VARCHAR(50) NOT NULL CHECK (provider IN ('vnpay', 'momo', 'cash')),
    amount INTEGER NOT NULL,
    status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'success', 'failed', 'expired')),
    transaction_id TEXT, -- ID from the gateway (e.g. VNPay TransactionNo)
    request_id TEXT UNIQUE, -- Idempotency key (e.g. generated by us sent to gateway)
    payment_url TEXT,
    return_url TEXT,
    ipn_data JSONB, -- Raw webhook payload
    metadata JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    completed_at TIMESTAMPTZ
);

-- Indexes
CREATE INDEX idx_payment_transactions_order_id ON public.payment_transactions(order_id);
CREATE INDEX idx_payment_transactions_request_id ON public.payment_transactions(request_id);
CREATE INDEX idx_payment_transactions_status ON public.payment_transactions(status);

-- Trigger for updated_at (reusing function from initial_schema)
CREATE TRIGGER update_payment_transactions_modtime
    BEFORE UPDATE ON public.payment_transactions
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE payment_transactions;

-- RLS Policies
ALTER TABLE public.payment_transactions ENABLE ROW LEVEL SECURITY;

-- Policy: Users can view their own order's payments
CREATE POLICY "Users can view their own payment transactions"
ON public.payment_transactions FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.orders o
        JOIN public.customers c ON o.customer_id = c.id
        WHERE o.id = payment_transactions.order_id
        AND c.auth_user_id = auth.uid()
    )
);

-- Policy: Staff/Admin can view all payment transactions
CREATE POLICY "Staff can view all payment transactions"
ON public.payment_transactions FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid()
        AND role IN ('admin', 'manager', 'staff', 'cashier')
    )
);

-- Policy: Service Role (Edge Functions) can do full access
-- Service role bypasses RLS by default, but we can be explicit if needed.
-- No explicit policy needed for service_role as it defaults to bypass RLS in Supabase client if configured correctly.
